### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by malgia** [santteegt/simple-ride#37]
App
- [ ] Add option to activate Email Notifications

Admin
- [ ] Add screen to manage completed and cancelled trips
- [ ] Add screen to manage admin users
- [ ] Add screen to manage places images
- [ ] Add screen to list users (probably also allow to deactivate/delete)
- [ ] Add screen to list reviews (probable also allow to ignore)

AWS
- [ ] Activate production mode on email notifications
